language: generic

branches:
  only:
    - master
    - /[0-9]+\.[0-9]+\.[0-9]+/

env:
  global:
    - APP_NAME=lookerbot

before_install:
  - wget https://hearst-hatchery.github.io/atlas/v3/vault.sh;
  - chmod +x vault.sh;
  - source vault.sh;

install:
  - docker pull quay.io/hearst/${APP_NAME}:${TRAVIS_COMMIT:0:7} || docker build -t quay.io/hearst/${APP_NAME}:${TRAVIS_COMMIT:0:7} .

script:
  - /bin/true

after_success: >-
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    wget https://hearst-hatchery.github.io/atlas/v3/stage_test_deploy.sh;
    chmod +x stage_test_deploy.sh;
    ./stage_test_deploy.sh "${APP_NAME}" ${TRAVIS_PULL_REQUEST} ${TRAVIS_COMMIT:0:7};
  fi;
deploy:
  - provider: script
    script: >-
      wget https://hearst-hatchery.github.io/atlas/v2/deploy_master.sh;
      chmod +x deploy_master.sh;
      ./deploy_master.sh;
      wget https://hearst-hatchery.github.io/atlas/v2/auto_deploy.sh;
      chmod +x auto_deploy.sh;
      ./auto_deploy.sh "${APP_NAME}" ${TRAVIS_COMMIT:0:7} kubefeature;
    on:
      branch: master
