kind: Service
apiVersion: v1
metadata:
  labels:
    app: lookerbot
  name: lookerbot
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: lookerbot
  selector:
    app: lookerbot
